name: Test with Azurite

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Install Azurite
      run: npx --yes --loglevel info azurite --version

    # use bash even on Windows to run Azurite in the background (& for asynchronous bash command)
    - name: Start Azurite
      shell: bash
      run: npx --yes azurite --silent --inMemoryPersistence &

    - name: Test
      run: dotnet test --no-build --verbosity normal
